[pytest]
#命令行参数
addopts = -v --alluredir=./temps --clean-alluredir

#注册标记
markers =
    smoke:冒烟测试
    username:用户管理
    api:接口测试
    ut:单元测试用例


disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

#日志配置
#日志文件配置
log_file = ./logs/frame.log
#日志级别
log_file_level = INFO
#日志格式
log_file_format = %(asctime)s %(levelname)s %(message)s